version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "vue",
    "ember"
  ]

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "scala"

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/subham-deepsource/Gigarepo"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[transformers]]
name = "gofumpt"

[[transformers]]
name = "google-java-format"

[[transformers]]
name = "dotnet-format"

[[transformers]]
name = "black"

[[transformers]]
name = "yapf"

[[transformers]]
name = "scalafmt"

[[transformers]]
name = "rustfmt"

[[transformers]]
name = "prettier"